### ISSUE TITLE
robot & refinery textures not loading

### ISSUE THREAD

**Issue by kotoroshinoto** [AlexIIL/BC-Temp-releases#2] opened 2016-02-25 03:22 UTC
not sure if its something about my mods setup, but can't see a texture on the items

**Comment by AlexIIL** [comment] 2016-02-25 13:47
It is a bug, however please don't report issues here. Use https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues instead.

Technically a duplicate of AlexIIL/Buildcraft_1.8_Issues#53.

**Closed by AlexIIL** 2016-02-25 13:47 UTC
